/**
 * action typs
 */

const SAVE_USER = 'SAVE_USER'
const GET_USERS = 'GET_USERS'
const UPDATE_USER = 'UPDATE_USERS'
const REMOVE_USER = 'REMOVE_USER'

const GET_TAGS = 'GET_TAGS'
const ADD_TAG = 'ADD_TAG'
const UPDATE_TAG = 'UPDATE_TAG'
const REMOVE_TAG = 'REMOVE_TAG'

const GET_CATEGORIES = 'GET_CATEGORIES'
const ADD_CATEGORY = 'ADD_CATEGORY'
const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
const DEL_CATEGORY = 'REMOVE_CATREGORY'

const GET_ARTICLES = 'GET_ARTICLES'
const ADD_ARTICLES = 'ADD_ARTICLES'
const UPDATE_ARTICLES = 'UPDATE_ARTICLES'
const DEL_ARTICLES = 'DEL_ARTICLES'

export {
  SAVE_USER,
  GET_USERS,
  UPDATE_USER,
  REMOVE_USER,
  GET_TAGS,
  ADD_TAG,
  UPDATE_TAG,
  REMOVE_TAG,
  GET_CATEGORIES,
  ADD_CATEGORY,
  UPDATE_CATEGORY,
  DEL_CATEGORY,
  GET_ARTICLES,
  ADD_ARTICLES,
  UPDATE_ARTICLES,
  DEL_ARTICLES
}
